version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net

  web:
    build: ./backend
    container_name: django
    command: ["/wait-for-it.sh", "db", "--", "python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend_net

volumes:
  mysql_data:

networks:
  backend_net:
