# Generated by Django 5.2.1 on 2025-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.TextField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.TextField()),
                ('action', models.CharField(choices=[('UPLOAD', '업로드'), ('DOWNLOAD', '다운로드'), ('DELETE', '삭제'), ('OVERWRITTEN_REMOVED', '덮어쓰기를 통한 삭제'), ('OVERWRITTEN_SAVED', '덮어쓰기를 통한 저장')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.uploadedfile')),
            ],
        ),
    ]
