# Generated by Django 5.2.1 on 2025-05-22 09:31

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PUSH', 'Push'), ('CHECKOUT', 'Checkout'), ('UNDO', 'Undo'), ('SQUASH', 'Squash')], max_length=20)),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('target_branch', models.CharField(default='main', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.TextField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('git_tracked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GitVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('commit_hash', models.CharField(max_length=40, unique=True)),
                ('commit_message', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('committed_at', models.DateTimeField()),
                ('branch_name', models.CharField(default='main', max_length=100)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_versions', to='workspace.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.TextField()),
                ('action', models.CharField(choices=[('UPLOAD', '업로드'), ('DOWNLOAD', '다운로드'), ('DELETE', '삭제'), ('OVERWRITTEN_REMOVED', '덮어쓰기를 통한 삭제'), ('OVERWRITTEN_SAVED', '덮어쓰기')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.uploadedfile')),
            ],
        ),
    ]
